site_name: Christine for NH
site_url: https://christine4nh.com
site_description: Re-Elect Christine Seibert for NH State Representative (Hillsborough District 21) | Manchester, Ward 1
copyright: Copyright &copy; 2018 - 2024 Christine for State Representative

nav:
  - Home: index.md
  - Endorsements: endorsements.md
  - Issues: issues.md
  - Vote: vote.md
  - 'Get Involved': involvement.md
  - Contact: contact.md
  - Donate: 'https://secure.actblue.com/donate/christine-4-nh'

theme:
  name: material
  custom_dir: ./docs/overrides
  logo: assets/images/christine_seibert_profile_icon_48.png
  favicon: assets/images/favicon.ico
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      scheme: christine4nh
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: christine4nh
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: christine4nh-dark
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - announce.dismiss
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - navigation.footer
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.sections
    - navigation.path
    - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.share
    - search.suggest
    - toc.integrate

extra:
  generator: true
  homepage: https://christine4nh.com
  social:
    - icon: custom/actblue
      link: https://secure.actblue.com/donate/christine-4-nh
      name: Donate
    - icon: material/facebook
      link: https://fb.com/christine4NHStateRep
      name: Facebook
    - icon: material/twitter
      link: https://x.com/christine4nh
      name: X
    - icon: material/email
      link: mailto:info@christine4nh.com
      name: Email
    - icon: material/github
      link: https://github.com/christine-seibert/christine-for-nh
      name: GitHub

extra_javascript:
  - javascript/extra.js
extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - mdx_truly_sane_lists
  - def_list
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons

plugins:
  - search:
      lang: en
  - git-revision-date-localized:
      enable_creation_date: true
  - privacy
  - open-in-new-tab
